name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.12.2
          cache: 'npm'
      - run: |
          npm ci
          npm run build --if-present
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          overwrite: true
